### ISSUE TITLE
Cannot Install...

### ISSUE THREAD

**Issue by kzssc** [rhydlewis/alfred-search-omnifocus#10]
Kindly help... thanks 👍 

1669 info run better-sqlite3@7.5.3 install node_modules/alfred-search-omnifocus/node_modules/better-sqlite3 prebuild-install || npm run build-release
1670 info run better-sqlite3@7.5.3 install { code: 1, signal: null }
1671 timing reify:rollback:createSparse Completed in 441ms
1672 timing reify:rollback:retireShallow Completed in 0ms
1673 timing command:install Completed in 5986ms
1674 verbose stack Error: command failed
1674 verbose stack     at ChildProcess.<anonymous> (/opt/homebrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:63:27)
1674 verbose stack     at ChildProcess.emit (node:events:527:28)
1674 verbose stack     at maybeClose (node:internal/child_process:1090:16)
1674 verbose stack     at Socket.<anonymous> (node:internal/child_process:449:11)
1674 verbose stack     at Socket.emit (node:events:527:28)
1674 verbose stack     at Pipe.<anonymous> (node:net:715:12)
1675 verbose pkgid better-sqlite3@7.5.3
1676 verbose cwd /Users/vpchris
1677 verbose Darwin 21.3.0
1678 verbose node v18.2.0
1679 verbose npm  v8.9.0
1680 error code 1
1681 error path /opt/homebrew/lib/node_modules/alfred-search-omnifocus/node_modules/better-sqlite3
1682 error command failed
1683 error command sh -c prebuild-install || npm run build-release
1684 error > better-sqlite3@7.5.3 build-release
1684 error > node-gyp rebuild --release
1685 error prebuild-install WARN install No prebuilt binaries found (target=18.2.0 runtime=node arch=arm64 libc= platform=darwin)
1685 error gyp info it worked if it ends with ok
1685 error gyp info using node-gyp@9.0.0
1685 error gyp info using node@18.2.0 | darwin | arm64
1685 error gyp info find Python using Python version 3.9.13 found at "/opt/homebrew/opt/python@3.9/bin/python3.9"
1685 error gyp info spawn /opt/homebrew/opt/python@3.9/bin/python3.9
1685 error gyp info spawn args [
1685 error gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
1685 error gyp info spawn args   'binding.gyp',
1685 error gyp info spawn args   '-f',
1685 error gyp info spawn args   'make',
1685 error gyp info spawn args   '-I',
1685 error gyp info spawn args   '/opt/homebrew/lib/node_modules/alfred-search-omnifocus/node_modules/better-sqlite3/build/config.gypi',
1685 error gyp info spawn args   '-I',
1685 error gyp info spawn args   '/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
1685 error gyp info spawn args   '-I',
1685 error gyp info spawn args   '/Users/vpchris/Library/Caches/node-gyp/18.2.0/include/node/common.gypi',
1685 error gyp info spawn args   '-Dlibrary=shared_library',
1685 error gyp info spawn args   '-Dvisibility=default',
1685 error gyp info spawn args   '-Dnode_root_dir=/Users/vpchris/Library/Caches/node-gyp/18.2.0',
1685 error gyp info spawn args   '-Dnode_gyp_dir=/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp',
1685 error gyp info spawn args   '-Dnode_lib_file=/Users/vpchris/Library/Caches/node-gyp/18.2.0/<(target_arch)/node.lib',
1685 error gyp info spawn args   '-Dmodule_root_dir=/opt/homebrew/lib/node_modules/alfred-search-omnifocus/node_modules/better-sqlite3',
1685 error gyp info spawn args   '-Dnode_engine=v8',
1685 error gyp info spawn args   '--depth=.',
1685 error gyp info spawn args   '--no-parallel',
1685 error gyp info spawn args   '--generator-output',
1685 error gyp info spawn args   'build',
1685 error gyp info spawn args   '-Goutput_dir=.'
1685 error gyp info spawn args ]
1685 error No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.
1685 error
1685 error No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.
1685 error
1685 error No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.
1685 error
1685 error Traceback (most recent call last):
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1502, in XcodeVersion
1685 error     version_list = GetStdoutQuiet(["xcodebuild", "-version"]).splitlines()
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1563, in GetStdoutQuiet
1685 error     raise GypError("Error %d running %s" % (job.returncode, cmdlist[0]))
1685 error gyp.common.GypError: Error 1 running xcodebuild
1685 error
1685 error During handling of the above exception, another exception occurred:
1685 error
1685 error Traceback (most recent call last):
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 45, in <module>
1685 error     sys.exit(gyp.script_main())
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 662, in script_main
1685 error     return main(sys.argv[1:])
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 654, in main
1685 error     return gyp_main(args)
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 639, in gyp_main
1685 error     generator.GenerateOutput(flat_list, targets, data, params)
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2455, in GenerateOutput
1685 error     writer.Write(
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 798, in Write
1685 error     self.WriteActions(
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 932, in WriteActions
1685 error     env = self.GetSortedXcodeEnv()
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2108, in GetSortedXcodeEnv
1685 error     return gyp.xcode_emulation.GetSortedXcodeEnv(
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1888, in GetSortedXcodeEnv
1685 error     env = _GetXcodeEnv(
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1743, in _GetXcodeEnv
1685 error     "XCODE_VERSION_ACTUAL": XcodeVersion()[0],
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1513, in XcodeVersion
1685 error     version = CLTVersion()  # macOS Catalina returns 11.0.0.0.1.1567737322
1685 error   File "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1551, in CLTVersion
1685 error     return re.search(regex, output).groupdict()["version"]
1685 error AttributeError: 'NoneType' object has no attribute 'groupdict'
1685 error gyp ERR! configure error 
1685 error gyp ERR! stack Error: `gyp` failed with exit code: 1
1685 error gyp ERR! stack     at ChildProcess.onCpExit (/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:261:16)
1685 error gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
1685 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
1685 error gyp ERR! System Darwin 21.3.0
1685 error gyp ERR! command "/opt/homebrew/Cellar/node/18.2.0/bin/node" "/opt/homebrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
1685 error gyp ERR! cwd /opt/homebrew/lib/node_modules/alfred-search-omnifocus/node_modules/better-sqlite3
1685 error gyp ERR! node -v v18.2.0
1685 error gyp ERR! node-gyp -v v9.0.0
1685 error gyp ERR! not ok
1686 verbose exit 1
1687 timing npm Completed in 6032ms
1688 verbose unfinished npm timer reify 1653491344924
1689 verbose unfinished npm timer reify:build 1653491349449
1690 verbose unfinished npm timer build 1653491349449
1691 verbose unfinished npm timer build:deps 1653491349450
1692 verbose unfinished npm timer build:run:install 1653491349455
1693 verbose unfinished npm timer build:run:install:node_modules/alfred-search-omnifocus/node_modules/better-sqlite3 1653491349455
1694 verbose code 1
1695 error A complete log of this run can be found in:
1695 error     /Users/vpchris/.npm/_logs/2022-05-25T15_09_04_879Z-debug-0.log

**Comment by rhydlewis** [comment]
Eeeek, sorry - no idea :( Did you run `npm install -g alfred-search-omnifocus`?

**Comment by khirasoft** [comment]
Same error here as well. I just installed and upgraded node/npm and used exactly the install command npm install -g alfred-search-omnifocus.
I am on an M1 running MacOS Ventura

**Comment by rhydlewis** [comment]
Duplicated by [issue 18](https://github.com/rhydlewis/alfred-search-omnifocus/issues/18). Problem is with better-sqlite3 and latest version of node (19). This workflow installs successfully using the LTS version of node (18.12.1). I don't have a fix for this using the latest version of node yet unfortunately.

**Comment by rhydlewis** [comment]
I think that's because the -g option (global) uses the system installed version of node (which I'm using is 19.0.1). Workaround I've used today is to install the LTS version as the system version of node.

**Comment by khirasoft** [comment]
Awesome! I installed version 18
```
brew uninstall node
brew install node@18
brew unlink node
brew link node@18
brew link --overwrite node@18
echo 'export PATH="/opt/homebrew/opt/node@18/bin:$PATH"' >> ~/.zshrc
```

And now the install worked 🙂

**Comment by rhydlewis** [comment]
Fixed by latest version of workflow

**Comment by yinan-c** [comment]
Thanks for the discussion!

I used node v18 installed by nvm, I tried v18.15 18.1 did not get any luck.
But then I followed the instruction to uninstall the node installed by brew, v20.6.1, and reinstall, relink node@18 from brew and echo it to PATH, now the installation works!
