### ISSUE TITLE
Search everything (`.se`) seems to be missing

### ISSUE THREAD

**Issue by JoelAnderson-UU** [rhydlewis/alfred-search-omnifocus#11]
Is it possible that the .se module is missing?  I can't seem to make it work, and it's the one I use the most. I often don't know whether a task is in my inbox or in the library, so I usually default to this, but it doesn't seem to be working in the rewritten version. 
> Searching for tasks in the Inbox and the Library: Search for all tasks within OmniFocus (whether you've processed them or not) with .se.

**Comment by rhydlewis** [comment]
You're right - I've not ported that from the old workflow. Will take a look and add it in the next release. Thanks for letting me know.
