### ISSUE TITLE
.sa finds results, but won't open them in OF

### ISSUE THREAD

**Issue by AvonGee** [rhydlewis/alfred-search-omnifocus#14]
I just (2022-08-21) installed the workflow, with OF 3.13.1, and macOS 12.5.1. Seems to work great, _except_ that when I use .sa to find actions (tasks), it successfully generates a list in Alfred, but when I select any of them nothing happens. OmniFocus isn't activated, and it doesn't switch to the action that I selected. So to be clear, if I invoke Alfred and type

- ".s ABC active action." then I see "ABC active action" as an Alfred result. I select it and bam, I'm in OF looking at it.
- ".sa ABC active action." then I see "ABC active action" as an Alfred result, but I select it and . . . the Alfred bar just closes and no OF. If OF is already foremost then it just sits there, and doesn't change the view.

I've opened up the workflow and tried to see what the issue might be but no luck. I can't find another command that doesn't work, it's just .sa, which would be the most useful one for me. Suggestions appreciated.

**Comment by AvonGee** [comment]
Follow-up!

I just noticed in the workflow that the .sa item had no connector to the omnifocus:///task/{query} URL item. It was only connected to the osascript item. I added a connection to the URL item, and now (surprise surprise) it works! That is, selecting an item in Alfred that the search returns opens it up in OF.

But here's the bad news: the .s and .sa commands seem to have some issue with the --activeOnly part of the query. Specifically:

- When I search using .sc, Alfred suggests results that all have the purple check mark icon beside them. And they are in fact completed.
- When I search with .s, it shows me a list of actions, some completed and some not. But they all have the green triangle icon beside them regardless of completion status. The funny part is that this isn't true for the .p command, which returns a list of items with some green triangles and some purple check marks.
- When I search with .sa, it shows me a list of actions all with green triangles. But some of them are actually completed. In other words, .sa produces exactly the same results as .s.

Could there be something wrong with the query? Or perhaps it's my database, though I have no problems at all within OF itself.

**Comment by AvonGee** [comment]
Nope, nope, my apologies. I think I've finally got it figured out: .s and .sa are both showing _dropped_ actions as active, not completed actions. I thought they were showing completed actions because they both returned items that weren't visible in the project. Then I realized the distinction.

So to summarize, I think there are two problems in the latest version of the workflow:

- The .sa item wasn't linked to the appropriate URL item.
- .s and .sa are both showing dropped items as active.

Perhaps either of both of these were known issues, although the first one seems kind of glaring!

Hope that's some help.

**Comment by rhydlewis** [comment]
@AvonGee thanks for this - you're correct on both issues. I hadn't spotted that Omni added supported for dropped tasks — [available since 2019](https://www.omnigroup.com/blog/omnifocus-dropped-actions) 😱 — so I'll look at a fix for that and release an update.

Thanks for the comprehensive bug report (and for doing all the hard work for me 👍)

**Comment by rhydlewis** [comment]
Fixed in [v1.0.11](https://www.npmjs.com/package/alfred-search-omnifocus/v/1.0.11)

`npm install -g alfred-search-omnifocus`
