### ISSUE TITLE
node modules error

### ISSUE THREAD

**Issue by stephen-a-mckay** [rhydlewis/alfred-search-omnifocus#15]
Hi

I'm really looking forward to getting this working, and appreciate your efforts!

I suspected this is probably not an issue with the workflow per se, but the version of node / npm and other bits & bobs I have installed on my mac.

Here's the error I'm seeing:

[10:41:51.877] Search OmniFocus JS[Script Filter] {
	"items": [
		{
			"icon": {
				"path": "/System/Library/CoreServices/CoreTypes.bundle/Contents/Resources/AlertStopIcon.icns"
			},
			"title": "Unable to connect to OmniFocus database (The module '/Users/stephenmckay/.nvm/versions/node/v17.1.0/lib/node_modules/alfred-search-omnifocus/node_modules/better-sqlite3/build/Release/better_sqlite3.node'\nwas compiled against a different Node.js version using\nNODE_MODULE_VERSION 102. This version of Node.js requires\nNODE_MODULE_VERSION 108. Please try re-compiling or re-installing\nthe module (for instance, using `npm rebuild` or `npm install`).)",
			"subtitle": "/Users/stephenmckay/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db"
		}
	]
}

What should I being doing to resolve this? Do I need to install a different version of node? 

Kind regards
Stephen

**Comment by rhydlewis** [comment]
Hi Stephen,

I think it's because your installation of mode (v17.1.0) is out of date compared the version I used to build the workflow (v18.7.0). If you update node to the latest version and then reinstall the workflow, it should work.

Let me know how you get on. 

Cheers,
Rhyd
