### ISSUE TITLE
How to run alfred commands for db?

### ISSUE THREAD

**Issue by rbieb** [rhydlewis/alfred-search-omnifocus#16]
Hi,

could you maybe give me a hint of how to run the db commands within alfred? I haven't been able to figure out on how to execute them.

<img width="696" alt="image" src="https://user-images.githubusercontent.com/6862450/192723276-11c13d10-5ac5-4ecd-aeab-c64d8d65d3b1.png">

Thanks!

**Comment by rhydlewis** [comment]
Hi,

1. Type in `find-of-db` into the Alfred window and press ↩
<img width="613" alt="Screenshot 2022-09-28 at 15 41 09@2x" src="https://user-images.githubusercontent.com/2102276/192809053-43643b4a-c750-457b-a0db-0beec3cadb04.png">
2. This will find and copy the location of the OmniFocus database (and also show it on screen)
<img width="1403" alt="Screenshot 2022-09-28 at 15 43 04@2x" src="https://user-images.githubusercontent.com/2102276/192809792-ac93b311-7922-46ad-ada3-c9d725b2f0f7.png">
3. Type in `set-of-db` into the Alfred window, hit the spacebar, press ⌘-V to paste the database location and then press ↩
<img width="613" alt="Screenshot 2022-09-28 at 15 45 52@2x" src="https://user-images.githubusercontent.com/2102276/192810158-c65500de-8b6d-4665-b0e2-0886015b2dd7.png">
4. That's it!

HTH,
Rhyd
