### ISSUE TITLE
Icons missing when using workflow with OmniFocus4

### ISSUE THREAD

**Issue by rhydlewis** [rhydlewis/alfred-search-omnifocus#20]

**Comment by rachelcsimmons** [comment]
I am having the same issue. Your file omnifocus.js contains a reference to /Applications/OmniFocus.app/Contents/Resources as the icon root, but apparently in OF 4 the icons are no longer in there. Not sure where they are, but you could add them to the workflow folder?

**Comment by rachelcsimmons** [comment]
As a temporary solve, I downloaded OF3, grabbed these images from the resources folder, and moved them into the OF4 resources folder

![active-small@2x](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/83f84012-e541-44b7-8d9a-12f6a0b74e33)
![completed-small@2x](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/b0974dd2-09fb-4645-936e-66486f375c76)
![dropped@2x](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/f2c06ba5-51ee-490c-a5d3-c5c36c5e0f1b)
![flagged@2x](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/abc2a716-8bc3-49ac-bff0-824614bc0fc9)
![on-hold@2x](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/7cca42ed-4b20-4046-a1ff-d87b12f8c81b)
![quickopen-folder@2x](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/2e59a4e6-6126-4e38-8c31-c037086ae8ed)

**Comment by rhydlewis** [comment]
Yeah... I've no idea where they are :( in OF4. I think I'll need to ship icons with the workflow itself but obviously can't ship Omni's images. Will have a think.

**Comment by rhydlewis** [comment]
Added icons from FontAwesome in place of OmniFocus icons in 1.0.13

**Comment by rachelcsimmons** [comment]
This is working! I noticed that the deferred icon is missing from the icons folder, so on first install, a deferred task/project has no icon, but I can confirm it does work if you add a deferred icon to the folder manually 
![image](https://github.com/rhydlewis/alfred-search-omnifocus/assets/66705427/a54c1b2b-cf7f-405b-9b6e-431b039f884b)

**Comment by rhydlewis** [comment]
Ah dammit, thanks for spotting that. Will sort out in next release.

**Comment by rhydlewis** [comment]
Fixed in 1.0.14
