### ISSUE TITLE
List and search perspectives broken

### ISSUE THREAD

**Issue by rhydlewis** [rhydlewis/alfred-search-omnifocus#3]
The query works according to the debug log but there's something odd included in the output back to Alfred.

`ERROR: Search OmniFocus JS[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Ealfred-search-omnifocus%3E4F1E36A8-A787-4FE7-9CE1-1CAB5F24717C)] JSON error: Garbage at end around line 17, column 0. in JSON:`

**Comment by klochowicz** [comment]
Perhaps alfy is swallowing some of the error messages by redirecting them to stdout, so that they're not available in Alfred's workflow debugger?

See: https://github.com/sindresorhus/alfy/issues/86

**Comment by rhydlewis** [comment]
Thanks but it's my own mistake... I've fixed it in version 1.0.2 (now available on NPM).

Fix: [https://github.com/rhydlewis/alfred-search-omnifocus/commit/ce22aa95057967158cbb8c92cb9fcceecc28f762](https://github.com/rhydlewis/alfred-search-omnifocus/commit/ce22aa95057967158cbb8c92cb9fcceecc28f762)
