### ISSUE TITLE
Suspected bug: Task titles containing apostrophes throw an error

### ISSUE THREAD

**Issue by apkawel** [rhydlewis/alfred-search-omnifocus#4]
First, thank you for this workflow, and for starting to rewrite it in JXA after it broke. This is one of the best workflows I have for Alfred, and it was a big relief to get it working again yesterday!

Bug report:

If the task title contains an apostrophe, the workflow throws an error similar to the one in the attached image. I imagine that it's either a regex issue or else that some part of the code needs to be escaped.

Example tasks:
* I've got a test
* plan for Dad's birthday

<img width="1082" alt="screen shot 2022-04-18 at 18 03 24" src="https://user-images.githubusercontent.com/32605043/163884789-bea2d955-36ca-4b6f-8157-1cc3265de223.png">
<img width="1082" alt="screen shot 2022-04-18 at 17 57 59" src="https://user-images.githubusercontent.com/32605043/163884669-374d5c5b-1d7b-403e-9d2e-3a4a58f8ff2e.png">

**Comment by rhydlewis** [comment]
Thanks for spotting that - annoying bug. Now fixed in v1.0.5.
