### ISSUE TITLE
TypeError when using any list operator (.lv, .lt, etc.)

### ISSUE THREAD

**Issue by mykmug** [rhydlewis/alfred-search-omnifocus#8]
When I use any of the list searches (`.lt` for example), I get an immediate error:

```JavaScript
TypeError: Cannot read properties of undefined 
(reading 'includes')
    at runWorkflow (file:///usr/local/lib/
node_modules/alfred-search-omnifocus/
index.js:42:15)
    at main (file:///usr/local/lib/node_modules/
alfred-search-omnifocus/index.js:35:9)
    at file:///usr/local/lib/node_modules/alfred-
search-omnifocus/index.js:137:1
    at async Promise.all (index 0)
```

**Comment by rhydlewis** [comment]
Ach - that's a silly bug, my bad. Will fix today.

**Comment by rhydlewis** [comment]
Fixed in https://www.npmjs.com/package/alfred-search-omnifocus/v/1.0.6

**Comment by mykmug** [comment]
Awesome job! I really love your extension -- it's making me switch from LaunchBar to Alfred. Great work. Thank you.

**Comment by rhydlewis** [comment]
Thanks for the feedback! Glad you find it useful.
