### ISSUE TITLE
Find-of-path had line breaks which caused error

### ISSUE THREAD

**Issue by rachelcsimmons** [rhydlewis/alfred-search-omnifocus#9]
FYI the install instructions did not work for me, but I discovered it was because there were line breaks in the path that got copied to my clipboard (see below), which turned into spaces on pasting in the 2nd step, so it was an invalid file path. Once I found the right path it was working again
```
/Users/****/Library/Group Containers/
34YW5XSRB7.com.omnigroup.OmniFocus/
com.omnigroup.OmniFocus3/
com.omnigroup.OmniFocusModel/OmniFocusDatabase.db
```

**Comment by rhydlewis** [comment]
Thanks for reporting this - will think about how to fix

**Comment by rhydlewis** [comment]
Fixed in v1.0.10

**Comment by NoodlesNinja** [comment]
Hello,

 When doing the find-of-db, I get the following code which looks fine (not line breaks)
`/Users/XXXXX/Library/Group Containers/34YW5XSRB7.com.omnigroup.OmniFocus/com.omnigroup.OmniFocus3/com.omnigroup.OmniFocusModel/OmniFocusDatabase.db`

However, when I tried to do the set-of-db, I get the following error message
`{"items" [{"title": "Couldn't find the 'node
binary", "subtile": "Symlink it to/usr/local/
bin "}]}`

**Comment by rhydlewis** [comment]
@NoodlesNinja glad you got it working after the reinstall 👍
